INSERT INTO products (
    ml_class,
    name_ru,
    name_en,
    aliases,
    density_g_per_cm3,
    calories_per_100g,
    proteins_per_100g,
    fats_per_100g,
    carbs_per_100g,
    source_nutrition,
    source_density,
    is_supported
) VALUES
('Apple', 'яблоко', 'apple', ARRAY['apples'], 0.8400, 52.00, 0.30, 0.20, 14.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Orange', 'апельсин', 'orange', ARRAY['oranges'], 0.8700, 47.00, 0.90, 0.10, 12.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Banana', 'банан', 'banana', ARRAY['bananas'], 0.9500, 89.00, 1.10, 0.30, 23.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Lemon', 'лимон', 'lemon', ARRAY['lemons'], 0.9500, 29.00, 1.10, 0.30, 9.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pear', 'груша', 'pear', ARRAY['pears'], 0.8500, 57.00, 0.40, 0.10, 15.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Strawberry', 'клубника', 'strawberry', ARRAY['strawberries'], 0.6000, 32.00, 0.70, 0.30, 7.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Mango', 'манго', 'mango', ARRAY['mangoes'], 1.0000, 60.00, 0.80, 0.40, 15.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pineapple', 'ананас', 'pineapple', ARRAY['pineapples'], 0.9000, 50.00, 0.50, 0.10, 13.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Cucumber', 'огурец', 'cucumber', ARRAY['cucumbers'], 0.9600, 15.00, 0.70, 0.10, 3.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Kiwi', 'киви', 'kiwi', ARRAY['kiwifruit'], 0.9800, 61.00, 1.10, 0.50, 15.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Corn', 'кукуруза', 'corn', ARRAY['sweet corn'], 0.7200, 86.00, 3.20, 1.20, 19.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Watermelon', 'арбуз', 'watermelon', ARRAY['watermelons'], 0.9600, 30.00, 0.60, 0.20, 7.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Cauliflower', 'цветная капуста', 'cauliflower', ARRAY[]::TEXT[], 0.6800, 25.00, 1.90, 0.30, 5.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Grape', 'виноград', 'grape', ARRAY['grapes'], 0.9600, 69.00, 0.70, 0.20, 18.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Avocado', 'авокадо', 'avocado', ARRAY['avocados'], 0.9500, 160.00, 2.00, 14.70, 8.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Peach', 'персик', 'peach', ARRAY['peaches'], 0.9000, 39.00, 0.90, 0.30, 9.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Eggplant', 'баклажан', 'eggplant', ARRAY['aubergine'], 0.6500, 25.00, 1.00, 0.20, 5.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pomegranate', 'гранат', 'pomegranate', ARRAY[]::TEXT[], 0.9500, 83.00, 1.70, 1.20, 18.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Cherry', 'вишня', 'cherry', ARRAY['cherries'], 0.9000, 63.00, 1.10, 0.20, 16.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pepper', 'перец', 'pepper', ARRAY['bell pepper', 'sweet pepper'], 0.6500, 31.00, 1.00, 0.30, 6.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Blueberry', 'голубика', 'blueberry', ARRAY['blueberries'], 0.7500, 57.00, 0.70, 0.30, 14.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Melon', 'дыня', 'melon', ARRAY[]::TEXT[], 0.9000, 34.00, 0.80, 0.20, 8.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Papaya', 'папайя', 'papaya', ARRAY[]::TEXT[], 0.8800, 43.00, 0.50, 0.30, 10.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Walnut', 'грецкий орех', 'walnut', ARRAY['walnuts'], 0.5500, 654.00, 15.20, 65.20, 13.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Guava', 'гуава', 'guava', ARRAY[]::TEXT[], 0.9600, 68.00, 2.60, 1.00, 14.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Apricot', 'абрикос', 'apricot', ARRAY['apricots'], 0.8500, 48.00, 1.40, 0.40, 11.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Beetroot', 'свёкла', 'beetroot', ARRAY['beet'], 1.0000, 43.00, 1.60, 0.20, 10.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cactus fruit', 'плод кактуса', 'cactus fruit', ARRAY['prickly pear'], 0.8500, 41.00, 0.70, 0.50, 9.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Cantaloupe', 'канталупа', 'cantaloupe', ARRAY[]::TEXT[], 0.9000, 34.00, 0.80, 0.20, 8.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Carambola', 'карамбола', 'carambola', ARRAY['star fruit'], 0.9500, 31.00, 1.00, 0.30, 6.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Chestnut', 'каштан', 'chestnut', ARRAY['chestnuts'], 0.5500, 196.00, 2.00, 1.40, 44.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Clementine', 'клементин', 'clementine', ARRAY[]::TEXT[], 0.8600, 47.00, 0.90, 0.20, 12.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Cocos', 'кокос', 'coconut', ARRAY['cocos'], 0.9500, 354.00, 3.30, 33.50, 15.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Dates', 'финики', 'dates', ARRAY['date'], 0.7500, 282.00, 2.50, 0.40, 75.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Fig', 'инжир', 'fig', ARRAY['figs'], 0.9000, 74.00, 0.80, 0.30, 19.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Ginger Root', 'корень имбиря', 'ginger root', ARRAY['ginger'], 0.8500, 80.00, 1.80, 0.80, 17.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Granadilla', 'гранадилла', 'granadilla', ARRAY[]::TEXT[], 0.9000, 97.00, 2.20, 0.70, 23.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Grape White', 'белый виноград', 'white grape', ARRAY['grape white', 'green grape'], 0.9600, 69.00, 0.70, 0.20, 18.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Grapefruit', 'грейпфрут', 'grapefruit', ARRAY[]::TEXT[], 0.9000, 42.00, 0.80, 0.10, 10.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Hazelnut', 'фундук', 'hazelnut', ARRAY['hazelnuts'], 0.6000, 628.00, 15.00, 60.80, 16.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Huckleberry', 'черника садовая', 'huckleberry', ARRAY[]::TEXT[], 0.7500, 37.00, 0.40, 0.10, 8.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Kaki', 'хурма', 'persimmon', ARRAY['kaki'], 0.9000, 70.00, 0.60, 0.20, 18.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Kohlrabi', 'кольраби', 'kohlrabi', ARRAY[]::TEXT[], 0.9000, 27.00, 1.70, 0.10, 6.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Kumquats', 'кумкват', 'kumquat', ARRAY['kumquats'], 0.8500, 71.00, 1.90, 0.90, 15.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Limes', 'лайм', 'lime', ARRAY['limes'], 0.9500, 30.00, 0.70, 0.20, 10.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Lychee', 'личи', 'lychee', ARRAY[]::TEXT[], 0.9200, 66.00, 0.80, 0.40, 16.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Mandarine', 'мандарин', 'mandarin', ARRAY['mandarine'], 0.8600, 53.00, 0.80, 0.30, 13.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Mangosteen', 'мангостин', 'mangosteen', ARRAY[]::TEXT[], 0.9000, 73.00, 0.40, 0.60, 18.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Maracuja', 'маракуйя', 'passion fruit', ARRAY['maracuja'], 0.9000, 97.00, 2.20, 0.70, 23.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Mulberry', 'шелковица', 'mulberry', ARRAY['mulberries'], 0.8000, 43.00, 1.40, 0.40, 9.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Nut Forest', 'лесной орех', 'forest nut', ARRAY['hazelnut'], 0.6000, 628.00, 15.00, 60.80, 16.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Passion Fruit', 'маракуйя', 'passion fruit', ARRAY['maracuja'], 0.9000, 97.00, 2.20, 0.70, 23.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pecan', 'пекан', 'pecan', ARRAY['pecans'], 0.5500, 691.00, 9.20, 72.00, 13.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pepino', 'пепино', 'pepino', ARRAY[]::TEXT[], 0.9200, 26.00, 0.40, 0.10, 6.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Physalis', 'физалис', 'physalis', ARRAY[]::TEXT[], 0.8500, 53.00, 1.90, 0.70, 11.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pitahaya Red', 'красная питахайя', 'red dragon fruit', ARRAY['pitahaya red', 'dragon fruit'], 0.9000, 57.00, 1.20, 0.10, 13.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Plum', 'слива', 'plum', ARRAY['plums'], 0.9000, 46.00, 0.70, 0.30, 11.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Pomelo', 'помело', 'pomelo', ARRAY[]::TEXT[], 0.9000, 38.00, 0.80, 0.04, 9.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Quince', 'айва', 'quince', ARRAY[]::TEXT[], 0.8500, 57.00, 0.40, 0.10, 15.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Rambutan', 'рамбутан', 'rambutan', ARRAY[]::TEXT[], 0.9000, 68.00, 0.90, 0.20, 16.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Raspberry', 'малина', 'raspberry', ARRAY['raspberries'], 0.6000, 52.00, 1.20, 0.70, 12.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Redcurrant', 'красная смородина', 'redcurrant', ARRAY['red currant'], 0.7500, 56.00, 1.40, 0.20, 13.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('Salak', 'салак', 'salak', ARRAY['snake fruit'], 0.8500, 82.00, 0.40, 0.40, 22.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE)
ON CONFLICT (ml_class) DO UPDATE SET
    name_ru = EXCLUDED.name_ru,
    name_en = EXCLUDED.name_en,
    aliases = EXCLUDED.aliases,
    density_g_per_cm3 = EXCLUDED.density_g_per_cm3,
    calories_per_100g = EXCLUDED.calories_per_100g,
    proteins_per_100g = EXCLUDED.proteins_per_100g,
    fats_per_100g = EXCLUDED.fats_per_100g,
    carbs_per_100g = EXCLUDED.carbs_per_100g,
    source_nutrition = EXCLUDED.source_nutrition,
    source_density = EXCLUDED.source_density,
    is_supported = EXCLUDED.is_supported,
    updated_at = CURRENT_TIMESTAMP;

