TRUNCATE TABLE products RESTART IDENTITY;

INSERT INTO products (
    ml_class,
    name_ru,
    name_en,
    aliases,
    density_g_per_cm3,
    calories_per_100g,
    proteins_per_100g,
    fats_per_100g,
    carbs_per_100g,
    source_nutrition,
    source_density,
    is_supported
) VALUES
('almond', 'миндаль', 'almond', ARRAY['almonds'], 0.6000, 579.00, 21.20, 49.90, 21.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('apple', 'яблоко', 'apple', ARRAY['apples'], 0.8400, 52.00, 0.30, 0.20, 14.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('apricot', 'абрикос', 'apricot', ARRAY['apricots'], 0.8500, 48.00, 1.40, 0.40, 11.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('artichoke', 'артишок', 'artichoke', ARRAY['artichokes'], 0.8000, 47.00, 3.30, 0.20, 10.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('asparagus', 'спаржа', 'asparagus', ARRAY[]::TEXT[], 0.7500, 20.00, 2.20, 0.10, 3.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('avocado', 'авокадо', 'avocado', ARRAY['avocados'], 0.9500, 160.00, 2.00, 14.70, 8.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('banana', 'банан', 'banana', ARRAY['bananas'], 0.9500, 89.00, 1.10, 0.30, 23.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('bean curd', 'тофу', 'bean curd', ARRAY['tofu', 'bean curd/tofu'], 0.9000, 76.00, 8.10, 4.80, 1.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('bell pepper', 'болгарский перец', 'bell pepper', ARRAY['capsicum', 'bell pepper/capsicum', 'sweet pepper', 'pepper'], 0.6500, 31.00, 1.00, 0.30, 6.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('blackberry', 'ежевика', 'blackberry', ARRAY['blackberries'], 0.7000, 43.00, 1.40, 0.50, 10.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('blueberry', 'голубика', 'blueberry', ARRAY['blueberries'], 0.7500, 57.00, 0.70, 0.30, 14.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('broccoli', 'брокколи', 'broccoli', ARRAY[]::TEXT[], 0.6500, 34.00, 2.80, 0.40, 6.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('brussels sprouts', 'брюссельская капуста', 'brussels sprouts', ARRAY['brussel sprouts'], 0.7000, 43.00, 3.40, 0.30, 9.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cantaloupe', 'канталупа', 'cantaloupe', ARRAY['cantaloup', 'cantaloup/cantaloupe'], 0.9000, 34.00, 0.80, 0.20, 8.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('carrot', 'морковь', 'carrot', ARRAY['carrots'], 0.8000, 41.00, 0.90, 0.20, 9.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cauliflower', 'цветная капуста', 'cauliflower', ARRAY[]::TEXT[], 0.6800, 25.00, 1.90, 0.30, 5.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cayenne', 'кайенский перец', 'cayenne pepper', ARRAY['cayenne spice', 'cayenne pepper', 'cayenne pepper spice', 'red pepper'], 0.4500, 40.00, 1.90, 0.40, 8.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('celery', 'сельдерей', 'celery', ARRAY[]::TEXT[], 0.6500, 16.00, 0.70, 0.20, 3.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cherry', 'вишня', 'cherry', ARRAY['cherries'], 0.9000, 63.00, 1.10, 0.20, 16.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('chickpea', 'нут', 'chickpea', ARRAY['garbanzo', 'chickpea/garbanzo'], 0.7500, 164.00, 8.90, 2.60, 27.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('chili', 'перец чили', 'chili pepper', ARRAY['chili vegetable', 'chili pepper', 'chili pepper vegetable', 'chilli', 'chilli vegetable', 'chilly'], 0.5500, 40.00, 1.90, 0.40, 8.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('clementine', 'клементин', 'clementine', ARRAY['clementines'], 0.8600, 47.00, 0.90, 0.20, 12.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('coconut', 'кокос', 'coconut', ARRAY['cocoanut', 'coconut/cocoanut', 'cocos'], 0.9500, 354.00, 3.30, 33.50, 15.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('corn', 'кукуруза', 'corn', ARRAY['edible corn', 'maize', 'edible corn/corn/maize', 'sweet corn'], 0.7200, 86.00, 3.20, 1.20, 19.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cucumber', 'огурец', 'cucumber', ARRAY['cuke', 'cucumber/cuke', 'cucumbers'], 0.9600, 15.00, 0.70, 0.10, 3.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('date', 'финик', 'date fruit', ARRAY['dates', 'date/date fruit'], 0.7500, 282.00, 2.50, 0.40, 75.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('eggplant', 'баклажан', 'eggplant', ARRAY['aubergine', 'eggplant/aubergine'], 0.6500, 25.00, 1.00, 0.20, 5.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('fig', 'инжир', 'fig', ARRAY['fig fruit', 'fig/fig fruit', 'figs'], 0.9000, 74.00, 0.80, 0.30, 19.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('garlic', 'чеснок', 'garlic', ARRAY['ail', 'garlic/ail', 'garlic bulb'], 0.6000, 149.00, 6.40, 0.50, 33.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('ginger', 'имбирь', 'ginger', ARRAY['gingerroot', 'ginger/gingerroot', 'ginger root'], 0.8500, 80.00, 1.80, 0.80, 17.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('strawberry', 'клубника', 'strawberry', ARRAY['strawberries', 'Strawberry'], 0.6000, 32.00, 0.70, 0.30, 7.70, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('gourd', 'тыква бутылочная', 'gourd', ARRAY['bottle gourd'], 0.7000, 14.00, 0.60, 0.10, 3.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('grape', 'виноград', 'grape', ARRAY['grapes'], 0.9600, 69.00, 0.70, 0.20, 18.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('green bean', 'стручковая фасоль', 'green bean', ARRAY['green beans'], 0.7000, 31.00, 1.80, 0.20, 7.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('green onion', 'зелёный лук', 'green onion', ARRAY['spring onion', 'scallion', 'green onion/spring onion/scallion'], 0.6500, 32.00, 1.80, 0.20, 7.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('tomato', 'помидор', 'tomato', ARRAY['tomatoes', 'Tomato'], 0.9500, 18.00, 0.90, 0.20, 3.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('kiwi fruit', 'киви', 'kiwi fruit', ARRAY['kiwi', 'kiwifruit'], 0.9800, 61.00, 1.10, 0.50, 15.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('lemon', 'лимон', 'lemon', ARRAY['lemons'], 0.9500, 29.00, 1.10, 0.30, 9.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('lettuce', 'салат латук', 'lettuce', ARRAY[]::TEXT[], 0.5000, 15.00, 1.40, 0.20, 2.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('lime', 'лайм', 'lime', ARRAY['limes'], 0.9500, 30.00, 0.70, 0.20, 10.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('mandarin orange', 'мандарин', 'mandarin orange', ARRAY['mandarin', 'mandarine'], 0.8600, 53.00, 0.80, 0.30, 13.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('melon', 'дыня', 'melon', ARRAY[]::TEXT[], 0.9000, 34.00, 0.80, 0.20, 8.20, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('mushroom', 'гриб', 'mushroom', ARRAY['mushrooms'], 0.6000, 22.00, 3.10, 0.30, 3.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('onion', 'лук', 'onion', ARRAY['onions'], 0.8000, 40.00, 1.10, 0.10, 9.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('orange', 'апельсин', 'orange', ARRAY['orange fruit', 'orange/orange fruit', 'oranges'], 0.8700, 47.00, 0.90, 0.10, 12.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('papaya', 'папайя', 'papaya', ARRAY[]::TEXT[], 0.8800, 43.00, 0.50, 0.30, 10.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('pea', 'горох', 'pea', ARRAY['peas', 'pea food', 'pea/pea food', 'green peas'], 0.7000, 81.00, 5.40, 0.40, 14.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('peach', 'персик', 'peach', ARRAY['peaches'], 0.9000, 39.00, 0.90, 0.30, 9.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('pear', 'груша', 'pear', ARRAY['pears'], 0.8500, 57.00, 0.40, 0.10, 15.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('persimmon', 'хурма', 'persimmon', ARRAY['kaki'], 0.9000, 70.00, 0.60, 0.20, 18.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('pickle', 'солёный огурец', 'pickle', ARRAY['pickled cucumber'], 0.9500, 12.00, 0.50, 0.20, 2.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('pineapple', 'ананас', 'pineapple', ARRAY['pineapples'], 0.9000, 50.00, 0.50, 0.10, 13.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('potato', 'картофель', 'potato', ARRAY['potatoes'], 0.7500, 77.00, 2.00, 0.10, 17.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('prune', 'чернослив', 'prune', ARRAY['prunes', 'dried plum'], 0.7500, 240.00, 2.20, 0.40, 64.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('pumpkin', 'тыква', 'pumpkin', ARRAY[]::TEXT[], 0.7500, 26.00, 1.00, 0.10, 6.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('radish', 'редис', 'radish', ARRAY['daikon', 'radish/daikon', 'radishes'], 0.9500, 16.00, 0.70, 0.10, 3.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('raspberry', 'малина', 'raspberry', ARRAY['raspberries'], 0.6000, 52.00, 1.20, 0.70, 12.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('sweet potato', 'батат', 'sweet potato', ARRAY['sweet potatoes', 'sweetpotato'], 0.8000, 86.00, 1.60, 0.10, 20.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('turnip', 'репа', 'turnip', ARRAY['turnips'], 0.8500, 28.00, 0.90, 0.10, 6.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('watermelon', 'арбуз', 'watermelon', ARRAY['watermelons'], 0.9600, 30.00, 0.60, 0.20, 7.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('zucchini', 'кабачок', 'zucchini', ARRAY['courgette', 'zucchini/courgette'], 0.7000, 17.00, 1.20, 0.30, 3.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE)
ON CONFLICT (ml_class) DO UPDATE SET
    name_ru = EXCLUDED.name_ru,
    name_en = EXCLUDED.name_en,
    aliases = EXCLUDED.aliases,
    density_g_per_cm3 = EXCLUDED.density_g_per_cm3,
    calories_per_100g = EXCLUDED.calories_per_100g,
    proteins_per_100g = EXCLUDED.proteins_per_100g,
    fats_per_100g = EXCLUDED.fats_per_100g,
    carbs_per_100g = EXCLUDED.carbs_per_100g,
    source_nutrition = EXCLUDED.source_nutrition,
    source_density = EXCLUDED.source_density,
    is_supported = EXCLUDED.is_supported,
    updated_at = CURRENT_TIMESTAMP;