TRUNCATE TABLE products RESTART IDENTITY;

INSERT INTO products (
    ml_class,
    name_ru,
    name_en,
    aliases,
    density_g_per_cm3,
    calories_per_100g,
    proteins_per_100g,
    fats_per_100g,
    carbs_per_100g,
    source_nutrition,
    source_density,
    is_supported
) VALUES
('soybean', 'соя', 'soybean', ARRAY['soybeans', 'soy bean', 'soya bean', 'edamame'], 0.7500, 173.00, 16.60, 9.00, 9.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('apple', 'яблоко', 'apple', ARRAY['apples'], 0.8400, 52.00, 0.30, 0.20, 14.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('banana', 'банан', 'banana', ARRAY['bananas'], 0.9500, 89.00, 1.10, 0.30, 23.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cabbage', 'капуста', 'cabbage', ARRAY['white cabbage'], 0.6500, 25.00, 1.30, 0.10, 5.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('capsicum', 'болгарский перец', 'capsicum', ARRAY['bell pepper', 'sweet pepper', 'pepper'], 0.6500, 31.00, 1.00, 0.30, 6.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cauliflower', 'цветная капуста', 'cauliflower', ARRAY[]::TEXT[], 0.6800, 25.00, 1.90, 0.30, 5.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('corn', 'кукуруза', 'corn', ARRAY['sweet corn'], 0.7200, 86.00, 3.20, 1.20, 19.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('cucumber', 'огурец', 'cucumber', ARRAY['cucumbers'], 0.9600, 15.00, 0.70, 0.10, 3.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('eggplant', 'баклажан', 'eggplant', ARRAY['aubergine'], 0.6500, 25.00, 1.00, 0.20, 5.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('garlic', 'чеснок', 'garlic', ARRAY['garlic bulb'], 0.6000, 149.00, 6.40, 0.50, 33.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('ginger', 'имбирь', 'ginger', ARRAY['ginger root'], 0.8500, 80.00, 1.80, 0.80, 17.80, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('grapes', 'виноград', 'grapes', ARRAY['grape'], 0.9600, 69.00, 0.70, 0.20, 18.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('lemon', 'лимон', 'lemon', ARRAY['lemons'], 0.9500, 29.00, 1.10, 0.30, 9.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('mango', 'манго', 'mango', ARRAY['mangoes'], 1.0000, 60.00, 0.80, 0.40, 15.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('onion', 'лук', 'onion', ARRAY['onions'], 0.8000, 40.00, 1.10, 0.10, 9.30, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('orange', 'апельсин', 'orange', ARRAY['oranges'], 0.8700, 47.00, 0.90, 0.10, 12.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('pear', 'груша', 'pear', ARRAY['pears'], 0.8500, 57.00, 0.40, 0.10, 15.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('peas', 'горох', 'peas', ARRAY['green peas', 'pea'], 0.7000, 81.00, 5.40, 0.40, 14.50, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('pineapple', 'ананас', 'pineapple', ARRAY['pineapples'], 0.9000, 50.00, 0.50, 0.10, 13.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('potato', 'картофель', 'potato', ARRAY['potatoes'], 0.7500, 77.00, 2.00, 0.10, 17.00, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('radish', 'редис', 'radish', ARRAY['radishes'], 0.9500, 16.00, 0.70, 0.10, 3.40, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('sweetpotato', 'батат', 'sweet potato', ARRAY['sweet potato', 'sweet potatoes'], 0.8000, 86.00, 1.60, 0.10, 20.10, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('tomato', 'помидор', 'tomato', ARRAY['tomatoes'], 0.9500, 18.00, 0.90, 0.20, 3.90, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE),
('watermelon', 'арбуз', 'watermelon', ARRAY['watermelons'], 0.9600, 30.00, 0.60, 0.20, 7.60, 'Initial MVP seed values; verify with selected nutrition dataset', 'Initial MVP estimated density; verify with selected density dataset', TRUE)
ON CONFLICT (ml_class) DO UPDATE SET
    name_ru = EXCLUDED.name_ru,
    name_en = EXCLUDED.name_en,
    aliases = EXCLUDED.aliases,
    density_g_per_cm3 = EXCLUDED.density_g_per_cm3,
    calories_per_100g = EXCLUDED.calories_per_100g,
    proteins_per_100g = EXCLUDED.proteins_per_100g,
    fats_per_100g = EXCLUDED.fats_per_100g,
    carbs_per_100g = EXCLUDED.carbs_per_100g,
    source_nutrition = EXCLUDED.source_nutrition,
    source_density = EXCLUDED.source_density,
    is_supported = EXCLUDED.is_supported,
    updated_at = CURRENT_TIMESTAMP;